import Head from "next/head";
import { useState } from "react";
import { BiUserPlus, BiX, BiCheck } from "react-icons/bi";
import Form from "../components/form/form";
import Table from "../components/Table/table";
import { useDispatch, useSelector } from "react-redux";
import {
  deleteAction,
  toggleChangeAction,
  updateAction,
} from "../redux/reducer";
import { deleteUser, getUsers } from "../lib/helper";
import { useQueryClient } from "@tanstack/react-query";

export default function Home() {
  const visible = useSelector(state => state.app.client.toggleForm);
  const deleteId = useSelector(state => state.app.client.deleteId);
  const queryclient = useQueryClient();

  const dispatch = useDispatch();

  const handleVisible = () => {
    dispatch(toggleChangeAction());
    dispatch(updateAction(null));
  };

  const deleteHandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery(["users"], getUsers);
      await dispatch(deleteAction(null));
    }
  };

  const cancelHandler = async () => {
    await dispatch(deleteAction(null));
  };
  return (
    <section>
      <Head>
        <title>Simple Crud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <div className="container mx-auto justify-between flex py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handleVisible}
              className="flex bg-indigo-500 text-white px-4 py-2  border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Employee
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
          {deleteId ? DeleteComponent({ deleteHandler, cancelHandler }) : null}
        </div>

        {visible ? <Form /> : null}

        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}

function DeleteComponent({ deleteHandler, cancelHandler }) {
  return (
    <div className="flex gap-5">
      <button>Are you sure?</button>
      <button
        className="flex bg-red-500 text-white px-4 py-2 rounded-md hover:bg-rose-500
      hover:border-red-500 hover:text-gray-50"
        onClick={deleteHandler}
      >
        Yes
        <span>
          <BiX color="rbg(255 255 255)" size={25} />
        </span>
      </button>
      <button
        onClick={cancelHandler}
        className="flex bg-green-500 text-white px-4 py-2 rounded-md hover:bg-green-500
      hover:border-green-500 hover:text-gray-50"
      >
        No
        <span>
          <BiCheck color="rbg(255 255 255)" size={25} />
        </span>
      </button>
    </div>
  );
}
